### ISSUE TITLE
Book Show: If the book is in my library:   Shows book info, book’s word list + add word action

### ISSUE THREAD

**Issue by aliyamerali** [Caleb1991/epeolatry_front_end#11]
If a book is already in the reader’s library, the page renders the book details, any words associated with the book, and a button to lookup a word from that book. 

Book’s word list: 
- Word, which links to word show page
- Words are shown in order of time added to the list, with most recently added words at the top 

Book details: 
- Title
- Author
- Genre
- Summary
- Shelf/status
- [Date started?]
- [Date completed?] 

FE will ping: 
GET (book’s word list) / epeolatry API
GET (get book details and status if in library) /  epeolatry API 

BE will need:
GET (check if book is in library) / Google Books API
GET (get book details) / Google Books API

**Comment by LawrenceWhalen** [comment]
We will need to use some logic in the BE to tell if a book is in our library by adding a book check call, so that we can easily tell if a book is added or not yet. There also isn't currently a back end call for a books words so that can't be displayed yet. Also waiting on the get single book endpoint so the show will need that.
